name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install TeX live
      run: sudo apt-get update && sudo apt-get install texlive texlive-publishers texlive-science texlive-bibtex-extra latexmk biber cm-super
      
    - name: Compile
      run: latexmk -pdf -bibtex main
      
    - name: Move
      run: mkdir github_artifacts && mv main.pdf github_artifacts

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: main
        path: github_artifacts

  deploy:

    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v4
      
    - name: Display structure of downloaded files
      run: ls -R
        
    - name: Move
      run: mkdir github_deploy && mv main github_deploy
      
    - name: Deploy on New Branch
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: github_deploy
        publish_branch: build
        force_orphan: true
