name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Install TeX live
      run: sudo apt-get update && sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super
      
    - name: Compile
      run: latexmk -pdf -bibtex main
      
    - name: Move
      run: mkdir github_artifacts && mv main.pdf github_artifacts

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: main
        path: github_artifacts

  deploy:

    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        path: github_artifacts
        
    - name: Move
      run: mkdir github_deploy && mv github_artifacts/main/main.pdf github_deploy
      
    - name: Deploy on New Branch
      uses: peaceiris/actions-github-pages@v3.1.12
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: github_deploy
        publish_branch: build
        force_orphan: true
